const CartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  DECREASE_ITEM_QTY: "DECREASE_ITEM_QTY",
}

export default CartActionTypes
